-- Generated by The DV7(s)
--! Made for getting all things
dv7={}
dv7:getApiFileByID(dv7(0x98347f88389348783b))
dv7:getApiFile(dv7.format(3455328752847567b))



dv7:require(folder('skyblock')
end
dv7:require(
  folder
  (
    {'bedwar',nil,'jailbreak-v2','eggwars','s'
    }
  )
)
